# Generated by Django 4.0.4 on 2022-05-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='deadline',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='module',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
