# Generated by Django 4.0.4 on 2022-05-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstate',
            name='state',
            field=models.IntegerField(choices=[(3, 'FAQ загрузка файла'), (4, 'FAQ получение вопросов'), (5, 'FAQ загрузка файла прошла успешно'), (6, 'FAQ получение ответа'), (7, 'Дедлайны номер курса')]),
        ),
    ]
