# Generated by Django 4.0.4 on 2022-05-29 17:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('is_actual', models.BooleanField(default=True)),
                ('materials', models.ManyToManyField(related_name='notifications', to='materials.material')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationsTimetable',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('send_time', models.DateTimeField()),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable', to='notifications.notification')),
            ],
        ),
    ]
