# Generated by Django 4.0.4 on 2022-05-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_actual',
        ),
        migrations.AddField(
            model_name='notificationstimetable',
            name='is_actual',
            field=models.BooleanField(default=True),
        ),
    ]
